#= require "config.js"
#= require "vendor/_jquery.js"
#= require "vendor/_lodash.js"
#= require "vendor/_backbone.js"
#= require "vendor/_backbone.marionette.js"
#= require "vendor/_jquery.fileupload.ui.js"
#= require "vendor/_jquery.iframe-transport.js"
#= require "vendor/_jquery.fileupload.js"
